---
- hosts: 192.168.0.133 
  remote_user: root
  tasks:
   - name: install nginx
     yum: name=nginx state=latest
   - name: start service
     shell: service nginx start
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
   - name: start service
     shell: systemctl start nginx.service
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 
